services:
  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: url-shortener-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=url_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: